version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region us-east-1 |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dakshin-registry

  build:
    commands:
      - mvn clean package -DskipTests
      - docker build -t dakshin-registry:latest .
      - docker tag dakshin-registry:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"studyplanner-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
